<?php

	return [

        'PropertyType' =>[
            'Residential / Apartment' => "Apartamento Padrão",
            'Residential / Home' => "Casa",
            'Residential / House' => "Casa Padrão",
        	'Residential / Sobrado' => "Sobrado",
            'Residential / Flat' => "Flat",
            'Residential / HABI' => "Habi",            
            'Residential / Two Story House' => "Duplex/Triplex",            
            'Residential / Apartment Hotel' => "Apartamento",
            'Residential / Land/Lot' => "Loteamento / Condomínio",
            'Residential / Farm/Ranch' => "Fazenda / Rancho",
            'Residential / Condo' => "Casa de Condomínio",
            'Commercial / Building' => "Prédio Inteiro",
            'Commercial / Residential Income' => "Casa Commercial",
            'Commercial / Office' => "Loja / Stúdio",
            'Commercial / Land/Lot' => "Conjunto Comercial",
            'Commercial / Industrial' => "Indústria",
            'Commercial / Retail' => "Loja / Salão",
            'Commercial / Agricultural' => "Galpão / Depósito",
            'Vacation / Home' => "Chácara",
            'Vacation / Aparment' => "Casa Rural",
            'Vacation / Farm/Ranch' => "Fazenda / Rancho",
            'Vacation / Condo' => "Condomínio"
        ],

        'Feature' => [

            'Fully Wired' => "Instalação Elétrica",
            'Generator' => "Gerador",
            'RV Parking' => "Estacionamento para trailers",
            'BBQ' => "Churrasqueira",
            'Bar' => "Bar",
            'Backyard' => "Quintal",
            'Alarm System' => "Sistema de Alarme",
            'Gated Community' => "Condomínio fechado",
            '24 Hour Security' => "Segurança 24 horas",
            'TV Security' => "Câmeras de Segurança",
            'Doorman' => "Porteiro",
            'Fire Alarm' => "Alarme de incêndio",
            'Kitchen' => "Cozinha",
            'Basement' => "Porão",
            'Living Room' => "Sala de estar",
            'Dining Room' => "Sala de jantar",
            'Study' => "Sala de Estudos",
            'Storage Room' => "Despensa",
            'Rooms' => "Quartos",
            'Hard Wood Floor' => "Piso de madeira nobre",
            'Carpeted Floor' => "Piso Revestido",
            'Ceramic Tile' => "Cerâmica",
            'Steam Room' => "Sauna",
            'Internet Connection' => "Internet",
            'Satellite Television' => " Tv por Satélite",
            'Cable Television' => "Televisão à cabo", 
            "Maid's Quarters" => "quartos de hospede",
            'Exterior View' => "Vista Externa",
            'Natural Gas' => "Gás",
            'Private Elevator' => "Elevador privado",
            'Elevator' => "Elevador",
            'Heating' => "Aquecedor",
            'Air Conditioning' => "Ar condicionado",
            'Ceiling Fan' => "Ventilador de teto",
            'Intercom' => "Interfone",
            'Marble/Granite' => "Mármore / Granito",
            'Parking Places' => "Área de estacionamento",
            'Parking Garage' => "Vagas de Garagem",
            'Garden' => "Jardim",
            'Jacuzzi/Hot Tub' => "Banheira de Hidromassagem",
            'Balcony/Terrace' => "Varanda / Terraço",
            'Pool' => "Piscina",
            'Fireplace' => "Lareira",
            'Wet Bar' => "Wet Bar",
            'Deck' => "Deck",
            'Lawn' => "Gramado",
            'Front Porch' => "Alpendre",
            'Corner Lot' => "Lote de esquina",
            'Landscaping' => "Paisagismo",
            'Lake View' => "Vista do lago",
            'Mountain View' => "Vista para Montanhas",
            'Ocean View' => "Vista para o mar",
            'Golf Course' => "Campo de golfe",
            'Water View' => "Vista para rio",
            'Estrato' => "Estrato",
            'Gym' => "Academia",
            'Movie Theater' => "Sala de Cinema",
            'Gourmet Area' => "Área Gourmet",

        ]

	];